"""Add new columns

Revision ID: 7ae282b5d506
Revises: 
Create Date: 2025-05-28 15:55:23.968977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae282b5d506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 第一步：添加允许为空的列
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('game_time', sa.Float(), nullable=True))
    
    # 第二步：设置默认值
    op.execute("UPDATE score SET player_name = '匿名玩家'")
    op.execute("UPDATE score SET difficulty = 'normal'")
    op.execute("UPDATE score SET game_time = 0.0")
    
    # 第三步：修改列为 NOT NULL
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('player_name', nullable=False)
        batch_op.alter_column('difficulty', nullable=False)
        batch_op.alter_column('game_time', nullable=False)
    
    # 第四步：为 created_at 设置默认值
    op.execute("""
        UPDATE score 
        SET created_at = CURRENT_TIMESTAMP 
        WHERE created_at IS NULL
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('game_time')
        batch_op.drop_column('created_at')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('player_name')

    # ### end Alembic commands ###